"""removed priority column from tasks table

Revision ID: 1c0513f660ec
Revises: e8c5e9a74aa1
Create Date: 2026-05-14 13:18:07.622918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0513f660ec'
down_revision: Union[str, Sequence[str], None] = 'e8c5e9a74aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
