"""rename id to category_id in categories

Revision ID: 76ec75b40c4b
Revises: c04b9271794e
Create Date: 2026-05-14 13:39:16.393915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ec75b40c4b'
down_revision: Union[str, Sequence[str], None] = 'c04b9271794e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("categories", 'id', new_column_name='category_id')
    op.drop_constraint(op.f('fk_tasks_category_id_categories'), 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_category_id_categories'), 'tasks', 'categories', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("categories", 'category_id', new_column_name='id')
    op.drop_constraint(op.f('fk_tasks_category_id_categories'), 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_category_id_categories'), 'tasks', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
