"""added new table and fk connection to tasks

Revision ID: c04b9271794e
Revises: a0c04ff31aa8
Create Date: 2026-05-14 13:30:45.161597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04b9271794e'
down_revision: Union[str, Sequence[str], None] = 'a0c04ff31aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.add_column('tasks', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_tasks_category_id_categories'), 'tasks', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_category_id_categories'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
